### ISSUE TITLE
Percentage numerator not rendered for levels and stats

### ISSUE THREAD

**Issue by mgpai22** [ergo-auction-house/frontend#1]
Hello for my [collection NFT](https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/3924e5f3ecedaecb1cd674ba851fd2dd3188f56cbdca7071fe6f17fa7cbf578f) the numerator for levels and stats do not appear to render. 

Please verify if this is a bug on my end or AH.

Also everything is bunched under traits. There should be separate categories.

**Comment by pyotrsky** [comment]
You're right. this seems a problem with the UI. Assigned to our team.

Regarding categories, you mean the 3 trait categories (Property, Stat, Level)?

**Comment by mgpai22** [comment]
Correct

**Comment by imght** [comment]
> Hello for my [collection NFT](https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/3924e5f3ecedaecb1cd674ba851fd2dd3188f56cbdca7071fe6f17fa7cbf578f) the numerator for levels and stats do not appear to render.
> 
> Please verify if this is a bug on my end or AH.

Hello, the bug of not rendering the trait value for levels and stats has been fixed. Please check again and let us know if the problem persists.

**Comment by mgpai22** [comment]
Looks good, however attributes, stats, and levels should be separated. This is how [opensea](https://opensea.io/assets/ethereum/0xb668beb1fa440f6cf2da0399f8c28cab993bdd65/3158) does it.
