### ISSUE TITLE
Where to enter custom bid amount?

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#11]
I only see a button to click to enter the minimum bid amount. Sometimes a bidder can't stay awake all night to monitor an auction and just wants to enter the maximum they are willing to play.

<img width="517" alt="bid" src="https://user-images.githubusercontent.com/129136234/228396424-8b141e30-332c-4c05-a666-9e379ae6b7bb.png">

**Comment by pyotrsky** [comment]
If you click on the bid button in the artwork's page, a modal will be opened and you can enter the bid amount you want.
