### ISSUE TITLE
Dark Mode - flashes white while loading

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#13]
Maybe the sitewide default background color should be dark grey so that dark-mode people don't get a super bright white page flash on reloading.

**Comment by anon-real** [comment]
@imght maybe instead of that, we should find a way to eliminate the flashing.

**Comment by imght** [comment]
The default theme and background color of the app is still Light Mode. But at the time of loading, the program is first loaded in dark mode, and after complete loading, the theme selected by the user for the program is executed, for this reason, for users who use the dark mode of the site, will not have the problem of flashing from light to dark mode.

**Comment by anon-real** [comment]
This has been resolved.
