### ISSUE TITLE
Owned Artwork - Tab Order & Naming

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#14]
The current tab names seem confusing to me
Artwork, Collection, Auctions, My Artworks, My Collections

Most people are collectors, so I think having that info is most relevant and should be on the left.

(Collector things left justified)  ------- (Artist things right justified)
Owned, Listed, Bids, Watch  <---------------------->  Minted

Owned - shows NFTs you own, currently hold in your wallet
Listed - shows NFTs you own, currently up for auction
Bids - shows NFTs you want, you are high bidder or have been outbid
Watch - shows NFTs you want, easily make bids or make offer
Minted - shows all the NFTs you have minted as an artist

---
In each of these subpages, there could be an NFT/Collection toggle (left justified) on the same line as grid size adjustment.

**Comment by Zimulakra** [comment]
This seems much clearer now.
It might be nice to add a "Bidding" tab to see what a user is bidding on or has been outbid on.

<img width="706" alt="Tabs" src="https://user-images.githubusercontent.com/129136234/229904310-caca5f3d-ca4e-40f6-a987-f43266894d1a.png">

**Comment by anon-real** [comment]
@Zimulakra  We'll have a per user activity page which shows all user's activities (just like the activity page)

Closing this issue for now.
