### ISSUE TITLE
Error updating my profile data

### ISSUE THREAD

**Issue by ladopixel** [ergo-auction-house/frontend#15]
I got an error message when I tried to update all my profile data at once. If I update them a little at a time it has left me without errors.

![Captura de Pantalla 2023-03-29 a las 21 08 28](https://user-images.githubusercontent.com/1231955/228645675-2819b238-f607-473a-80b1-dedcc7ccc96e.png)

**Comment by Therisaa** [comment]
I made some changes and I think this error won't appear anymore. Can you please check it again?

**Comment by ladopixel** [comment]
It let me modify everything correctly. 

Although I think it would also be very nice if once the profile data is modified it would redirect to somewhere on the web. Just showing the popup that the modification was successful gives the feeling of incomplete process.

![Captura de Pantalla 2023-04-04 a las 11 44 00](https://user-images.githubusercontent.com/1231955/229753551-f69083d6-acae-4232-b6e6-6165ff0a5a22.png)

**Comment by Therisaa** [comment]
I can add a button or a link on the popup that takes us to the user page. This way, we can check whether the information was updated or not.

**Comment by ladopixel** [comment]
It can be a good idea the button or link to inform.
Although I think that the same action that the button performs, should be performed by the close button of the popup.
