### ISSUE TITLE
Profile Bio Line

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#16]
Profile Bio line is showing up on two lines even though it is fairly short.

<img width="439" alt="Bio" src="https://user-images.githubusercontent.com/129136234/228661552-96ecf697-4310-4c94-aa88-7fe3d2ba133b.png">

**Comment by imght** [comment]
Hello, the mentioned problem has been checked and solved, please let us know if the problem still persists, thanks.

**Comment by anon-real** [comment]
This has been resolved.
