### ISSUE TITLE
Submitting Bid Fail - 404

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#17]
On this page
https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/6a5272dc63d38b48e4ab7360f6ee193c6ad1b2aeda6375c41741df22c98969a4

After entering my bid amount on the popup I got this error.
"Request failed with status code 404"

**Comment by 11001101110101110001111010111110101** [comment]
Please check it right now.

**Comment by anon-real** [comment]
Resolved. @Zimulakra please report if you see this again.
