### ISSUE TITLE
Error trying to bid an NFT

### ISSUE THREAD

**Issue by ladopixel** [ergo-auction-house/frontend#18]
I don't know if this is a one-off for this NFT or a bug. The other NFTs have let me bid correctly.

https://user-images.githubusercontent.com/1231955/228671570-51f62345-173c-4d6e-9a14-bab40629d7c6.mov

**Comment by pyotrsky** [comment]
Seems the same problem as #17

**Comment by 11001101110101110001111010111110101** [comment]
Please check it right now.

**Comment by ladopixel** [comment]
Right now.

https://user-images.githubusercontent.com/1231955/228905709-deb739bc-c625-4d6d-bf6a-7235a89e6042.mov

**Comment by 11001101110101110001111010111110101** [comment]
Fixed.

**Comment by anon-real** [comment]
This has been resolved.
