### ISSUE TITLE
Minting -15 units of NFT

### ISSUE THREAD

**Issue by ladopixel** [ergo-auction-house/frontend#19]
I think it would be better to verify the units to be minted before having to sign the transaction. 
In the video I try to mint -15 units.

https://user-images.githubusercontent.com/1231955/228675425-ab08d26a-5cf3-4bbe-af41-cc9ea8ff20ea.mov

**Comment by pyotrsky** [comment]
Done. Would you please try it again? @ladopixel

**Comment by ladopixel** [comment]
When I try -1 it tells me that it is impossible, it must be greater than 1, but I enter 1.1 and it still lets me sign and then shows the error.

**Comment by Therisaa** [comment]
I fixed this issue. Would you please check it again?

**Comment by ladopixel** [comment]
Now it worked correctly, I have not been able to generate any errors entering the number.
