### ISSUE TITLE
Sharing on Twitter

### ISSUE THREAD

**Issue by ladopixel** [ergo-auction-house/frontend#20]
It seems to create the message cut off, without the full text and link.

https://user-images.githubusercontent.com/1231955/228746704-0c55706c-f35d-4879-8978-c6a8957781da.mov

**Comment by ladopixel** [comment]
I tested creating an NFT with the # symbol in the name and the message shared on Twitter gives the same error. I think that # character generates the error.

![Captura de Pantalla 2023-03-30 a las 8 27 05](https://user-images.githubusercontent.com/1231955/228748809-66934e7e-43b0-4edf-8286-cbbaeefc7a6f.png)

**Comment by imght** [comment]
Hello, I think we have been able to solve the problem. Please let me know if the problem persists, thanks

**Comment by ladopixel** [comment]
I just tried it and it worked fine!
