### ISSUE TITLE
No artwork image displayed in the preview

### ISSUE THREAD

**Issue by ladopixel** [ergo-auction-house/frontend#22]
I have not yet managed to see any images at this step of the auction.

https://user-images.githubusercontent.com/1231955/228756302-d5c6d0db-b07f-4380-9e88-323712b587ff.mov

**Comment by Therisaa** [comment]
I fixed the image URLs on this page. Would you please check it again?

**Comment by anon-real** [comment]
This seems resolved.

**Comment by ladopixel** [comment]
I don't know if it's just me or if the image is a bit distorted, I don't know if it's that it doesn't keep the ratio correctly or that it shows a more vertical shape than 1:1

I'm not sure, but it looks a bit strange in the second step.

![Captura de Pantalla 2023-04-04 a las 6 45 55](https://user-images.githubusercontent.com/1231955/229689523-63b0bd2f-e518-4038-bde6-5683fb240e31.png)
![Captura de Pantalla 2023-04-04 a las 6 45 18](https://user-images.githubusercontent.com/1231955/229689521-b24124f3-773a-4bb7-b700-2c026f0a291c.png)
