### ISSUE TITLE
Create a Collection - Image size

### ISSUE THREAD

**Issue by ERGkleure** [ergo-auction-house/frontend#23]
Create Collection

I think it would be great to indicate the appropriate size for each one or at least the proportion, as I have tried several images and most of them are cut off somewhere in the preview, it would save time indicating some measure like 1500 x 500 or square, etc.. any information would be good.

![1](https://user-images.githubusercontent.com/90791980/228851593-52a9896b-9967-4393-acdb-c8078cd1c815.png)

**Comment by imght** [comment]
Hi, we have added a description of their use as well as suggested dimensions for the images that the user can upload. We hope it is helpful.

**Comment by anon-real** [comment]
This is resolved. @ERGkleure please report if you find it confusing again.
