### ISSUE TITLE
Socials

### ISSUE THREAD

**Issue by Lycan2022** [ergo-auction-house/frontend#26]
For the creation of collections, I'm missing Discord as an option in the Socials section. It's is one of the main goto's after twitter and insta. Maybe add tiktok too, although there is a lot of scrutiny on for that now.

**Comment by Allcyberpunk** [comment]
I have seen that you have added a Discord icon, but you can only see it and it directs you to Discord.com, but inside the profile you can't edit and put your own Discord.

![discord](https://user-images.githubusercontent.com/129761015/229537799-366b48f3-0d18-4958-a8c5-9fea91f8e08b.PNG)

![discord2](https://user-images.githubusercontent.com/129761015/229537840-adffa399-0260-46d7-8338-2d478cb0da00.PNG)

**Comment by Therisaa** [comment]
I added a field for discord ID in the profile setting page. You can now set your discord ID.
