### ISSUE TITLE
The bidding price is displayed incorrectly within the collection - O ERG

### ISSUE THREAD

**Issue by ERGkleure** [ergo-auction-house/frontend#27]
Trending in all NFT - Here is the correct bid price, 10 ERG

![4](https://user-images.githubusercontent.com/90791980/228869630-d722a857-fdb7-4b9f-b795-02509ead3920.png)

If I do a search for the Collection, in this case "Collection 1" the same NFT appears with the bid price 0 ERG, instead of 10 ERG

![5](https://user-images.githubusercontent.com/90791980/228870374-7322ec67-d72d-4ec0-a38d-861720e99d06.png)

**Comment by anon-real** [comment]
This is resolved.

**Comment by anon-real** [comment]
@imght We should add auctions tab to the collection page. Will close the issue once that is done.
