### ISSUE TITLE
Redirection after minting

### ISSUE THREAD

**Issue by ladopixel** [ergo-auction-house/frontend#29]
When a token is finished minting it just shows a popup that it was minted successfully.
I think it's a good idea to show the popup and redirect to another place when it closes, for example redirect to My items.

As it is now staying at the last minting screen, it me raises the question of whether it was minted correctly or I can hit it twice thinking that the minting was not performed correctly.

https://user-images.githubusercontent.com/1231955/229278701-b3179805-ff22-4e06-b4b3-ae4a559b79fa.mov

**Comment by anon-real** [comment]
Makes sense. Let's do this for minting collections (redirects to my collections) and starting auctions (redirects to auctions) as well.
