### ISSUE TITLE
Can't load metadata

### ISSUE THREAD

**Issue by WalrusDAO** [ergo-auction-house/frontend#30]
I can't work out how to enter the metadata. On Auction House V2 I can simply copy and paste the metadata using the 721 standard.

**Comment by anon-real** [comment]
@WalrusDAO In v2, people used to enter their metadata in the description field. This was just a workaround for the lack of standard we had. Now we have a defined and [accepted standard](https://github.com/ergoplatform/eips/pull/69). So now you should fill the fields that the new UI offers (traits section for example) and that automatically takes care of following the standard for metadata.

Later, we will have file parsers which allows artists to submit their metadata file and we fill the fields automatically based on that.

**Comment by Lycan2022** [comment]
Isn't it a possibilities to do an either/or option? Generally, I prepare a JSON description in text editor and than copy paste this to the description box. Now that would mean copy pasting line from the editor to V3.
This is prone to unnecessary errors and can be very tedious especially with a bigger amount of mints.

**Comment by WalrusDAO** [comment]
I can't add any metadata traits for some reason. Under 'property', when I add text to 'key', it doesn't save and goes blank when I move out of that box.

I also agree with @Lycan2022. Adding metadata in this new way would be very time consuming and easy to make errors.

**Comment by Lycan2022** [comment]
You have to click 'add'. Pushing enter doesnt work.

What I do wonder, and I havent checked it, once you have added it, does it get logged in a database for later reuse and easy access or does it have to be added every time we mint something.

**Comment by WalrusDAO** [comment]
@Lycan2022 Easy when you know how. Thanks. That's good feedback for @anon-real. Now I know how that works, I'll play around with it.

**Comment by anon-real** [comment]
@Lycan2022 yes it gets indexed for that collection and you don't have to add it every time.

Also, adding metadata using JSON can be done later (after we know the fundamentals are without bugs) more or less easily.
