### ISSUE TITLE
Spelling error Mined instead of Minted

### ISSUE THREAD

**Issue by Lycan2022** [ergo-auction-house/frontend#32]
Notification says artwork/collection is mined instead of minted.

![image](https://user-images.githubusercontent.com/120051677/229484767-c5c1378e-59da-4c50-927d-6471710661de.png)

**Comment by anon-real** [comment]
@Therisaa let's change "mined" for artwork and collection creation to "minted"

**Comment by Therisaa** [comment]
Done.
