### ISSUE TITLE
Metadata entry use unclear

### ISSUE THREAD

**Issue by Lycan2022** [ergo-auction-house/frontend#33]
For me it is unclear what the idea is behind the several topics of metadata e.g. propery, stat, level. Maybe having a ?  hover button with a quick description of supposed data entry can fix this? Or a help-link?

![image](https://user-images.githubusercontent.com/120051677/229487839-15b7c307-2fd1-4585-b2a8-9fb3b0fabc7b.png)

**Comment by anon-real** [comment]
<img width="448" alt="Screenshot 2023-04-14 at 10 08 05 PM" src="https://user-images.githubusercontent.com/68861503/232184303-d7ba2622-540c-4667-968b-53170c062af6.png">
