### ISSUE TITLE
Single/Multimint options

### ISSUE THREAD

**Issue by Lycan2022** [ergo-auction-house/frontend#34]
Why start minting from one page for both single and multimints? 
It seems more practical to split the two and have an option for a single mint and multimint in the drop down 'create' menu e.g.:

- Mint
- Multimint
- Collection

in this way, you can avoid double work as well while issueing and preparing the mint.

**Comment by Lycan2022** [comment]
Maybe even add 
- List 
as an option in that dropdown.

**Comment by anon-real** [comment]
@Lycan2022 I personally think the current approach is better as it is only an extra click for single mints but it avoids having multiple pages for the same purpose.

But having the list option in the dropdown is a good idea.

**Comment by anon-real** [comment]
@Therisaa let's add "Listings" button to the profile dropdown which redirects to user's listings tab in his profile page.

**Comment by Therisaa** [comment]
Done!
