### ISSUE TITLE
Error behaviour Drop down menu Explore NFTs

### ISSUE THREAD

**Issue by Lycan2022** [ergo-auction-house/frontend#35]
Dropdown menu in 'Explore NFTs' snaps back after scrolling down, making only the top 4 options selectable.

![image](https://user-images.githubusercontent.com/120051677/229490816-d1f50921-7a8e-4f51-a2be-ca3d409940be.png)

**Comment by imght** [comment]
Hi, thanks for your help. We tried to solve the problem as much as possible, now there is no scrolling problem.
