### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Allcyberpunk** [ergo-auction-house/frontend#36]
![application error](https://user-images.githubusercontent.com/129761015/229532485-61ce722d-11d9-4fc1-a4ce-822b1f627d8a.PNG)

An error occurred after minting two NFTs and clicking on the notification bell emoticon.

**Comment by anon-real** [comment]
@Allcyberpunk is it possible for you to open your browser console (F12) go to networks tab, open the notification center. Then you should see a few requests being sent like the following image:
<img width="1437" alt="Screenshot 2023-04-03 at 2 57 15 PM" src="https://user-images.githubusercontent.com/68861503/229636472-748b2e73-d29a-4952-9ca5-698d8ac87a7c.png">

Could you share the response of those requests (those that are non-empty) here?

**Comment by Allcyberpunk** [comment]
Whenever I click on the bell I get that error. 

![console](https://user-images.githubusercontent.com/129761015/229861704-74d4f069-9c5b-486e-ab6d-773742ca694e.PNG)

**Comment by Therisaa** [comment]
Do you get this error on every page? Or it just happens after minting an item? 
It would be really nice if you could send me the response to the request. The request's name is ?page=1&limit=5 and It appears exactly after clicking on the bell icon.
A screenshot from the console section that shows the error message will also be helpful. Like this:
![console](https://user-images.githubusercontent.com/129192433/230071421-4a11201b-982a-4412-a7a6-7cf62f3a9757.JPG)

**Comment by anon-real** [comment]
@Allcyberpunk are still getting this error?

**Comment by Allcyberpunk** [comment]
I get the error every time I press the bell, no matter what I do and no matter where I am on the web, every time I touch the bell again I get the error.

**Comment by Allcyberpunk** [comment]
![error](https://user-images.githubusercontent.com/129761015/231474397-d85db05b-d0d0-4fbf-b68e-243050a24af5.PNG)

I hope this screenshot is helpful.

**Comment by Therisaa** [comment]
Thank you for the screenshot. I think I found the problem and fixed it. Can you please check if you are still getting this error or not?

**Comment by anon-real** [comment]
@Allcyberpunk are you still getting this error?

**Comment by Allcyberpunk** [comment]
I think it's solved, notifications open perfectly.
