### ISSUE TITLE
invalid: Problem in broadcasting or saving Transactions.

### ISSUE THREAD

**Issue by Allcyberpunk** [ergo-auction-house/frontend#37]
![transactions](https://user-images.githubusercontent.com/129761015/229535451-bbd92a08-8cd1-4206-afc0-f829c2b87ed2.PNG)

When I paid for a bid, Nautilus opened, I signed the transaction and I got this message.

**Comment by anon-real** [comment]
Could you provide the link to the auction?

**Comment by Allcyberpunk** [comment]
Right now I don't know what the link is exactly, sorry. I will keep trying and if it comes up again I will send you the link.

**Comment by anon-real** [comment]
Closing this issue. @Allcyberpunk please let us know if you see this again.

**Comment by Allcyberpunk** [comment]
It happened to me again. Here are 3 screenshots where you can see the error, the nft I tried to bid and the error in console.

![broadcasting](https://user-images.githubusercontent.com/129761015/231479260-db409825-dc76-46d9-946e-e73ac00fd3e4.PNG)

![broadcasting2](https://user-images.githubusercontent.com/129761015/231479330-aa53c7a9-011f-49e2-93e4-e1bfa2c3e0ca.PNG)

![broadcasting3](https://user-images.githubusercontent.com/129761015/231479365-0c89d9bf-3f7b-4260-805d-74b50b0c3166.PNG)
