### ISSUE TITLE
Doubt: Can't you already put an auction and also a selling price?

### ISSUE THREAD

**Issue by Allcyberpunk** [ergo-auction-house/frontend#38]
![doubt](https://user-images.githubusercontent.com/129761015/229542387-4cfab92a-b256-4861-8f36-ba2f18e4ea80.PNG)

Doubt: Can't you already put an auction and also a selling price?

I understand that you can put an auction or a fixed price, but not both at the same time, no?
This was an option that I liked a lot in V2 and used a lot.

I have the doubt because I do not know if it is something that has been removed or I have not understood how to use it.

**Comment by anon-real** [comment]
@Allcyberpunk Yes, these two are separated now. So currently we have three types:
- timed which allows buyers to bid
- fixed
- declining price -- price declines over time. This is kind of like the middle ground for timed and fixed

**Comment by anon-real** [comment]
@Allcyberpunk do you think with these options, we still need the type with both bid and buy options? That would complicate things a bit.

**Comment by Allcyberpunk** [comment]
I sincerely believe that it is a fundamental tool, in my particular case almost 80% of my collection has been sold with the direct purchase option. Beyond my case, I think it is something that is used a lot, it gives the option to buy directly in a bidding war. I have seen that it has been VERY much used by people. If you have doubts you can make a consultation to the users, I am convinced that they will want this option to be included. Of course I do not want to bring problems or delay your work, I take this opportunity to congratulate you and the team as it is getting a great website!

**Comment by anon-real** [comment]
@Allcyberpunk thanks for the feedback. I'll look into how hard it would be to incorporate that. However, given what you said, even if we don't include that for the release, it will be added shortly after.

Also, we'll have offer options too. NFTs that are not even listed can receive offers and the owner can accept or reject.

**Comment by maritsaart** [comment]
@anon-real
Is it possible to add an option (for lister) to cancel the auction (timed/fixed/declining)? Like on SH.

**Comment by Allcyberpunk** [comment]
@anon-real I am very glad you told me that it is an option that will include the ability to put an auction and at the same time a sale price, as in the current v2, is a tool that I see very useful. Even if it can not be included at launch and will be done later I think it's great and I appreciate it immensely. You are doing a great job!
