### ISSUE TITLE
Bidder and Seller?

### ISSUE THREAD

**Issue by Allcyberpunk** [ergo-auction-house/frontend#39]
I just bid this NFT and nowhere does my wallet appear as "bidder" as it was in V2, no? or where can I see that data?

On the other hand, where is the "seller" indicated? Is it the one that indicates "Created by"? Created gives me the feeling that it is the one who mints, not the one who sells. 

![seller-bidder](https://user-images.githubusercontent.com/129761015/229549201-5c0d9ce9-0ac7-42ff-a3a6-dc23a4611392.PNG)

**Comment by pyotrsky** [comment]
We are working on the feature you mentioned, to show the users which artworks they bid on.

The seller is the one who currently has the artwork in their wallet and has listed it. And you are right: "Created by" indicates the one who has minted the artwork in the first place. "Created by" does not change for an artwork, however an artwork may get listed multiple times, each time with a different seller. The seller is denoted by "Listed by" right below the name of the artwork.

**Comment by anon-real** [comment]
We should change Created by to Minted by.

**Comment by anon-real** [comment]
@Allcyberpunk thanks for the suggestion! We have missed the bidder information, it will be added.

**Comment by anon-real** [comment]
This is done.
