### ISSUE TITLE
Only 1 of my 2 nfts showing up in "My Artworks"

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#4]
I created 2 NFTs at one time and only 1 is showing up.

Hoari - Before & After

Token ID - is showing 383238982702f293e21518d218547a0d49bf3661639683926af71cdae3bcd6a7

Token ID - not showing
f7e196d1bf63bdb9e6e6be7f27818007698fc178f0674f86c42a636ede2a5790

**Comment by Zimulakra** [comment]
One of my NFTs is still not showing up in "My Artworks" but it is showing up in Nautilus

Hoari - Before & After
Token ID - f7e196d1bf63bdb9e6e6be7f27818007698fc178f0674f86c42a636ede2a5790

**Comment by Zimulakra** [comment]
The missing NFT is now showing up in my Auction House "Owned Artwork"
Hoari - Before & After
Token ID - f7e196d1bf63bdb9e6e6be7f27818007698fc178f0674f86c42a636ede2a5790

**Comment by pyotrsky** [comment]
~It seems appearing in your profile: https://auctionhouse-testnet-qa78f.ondigitalocean.app/user/3WxsZAT9oKRanzUBtoJYNZa4gcxQVtGN2zSG7iBfjRPm5sr9iLzZ?tab=0&tabName=artwork~

~But not in your owned artworks tab. Seems like an issue with our API. Let us check it.~

UPDATE: resolved.
