### ISSUE TITLE
Duplicate events in sales history

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#41]
https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/67b08b7ad0c350cb97cf33a027cd7d1b2e64affe27d3bf1682aed66bdaccc16a

<img width="611" alt="duplicate" src="https://user-images.githubusercontent.com/129136234/229906532-c4eee4ad-620e-478c-8583-cb3531623cd0.png">

**Comment by anon-real** [comment]
@Zimulakra the old ones are because of the issue we had. But we shouldn't see this anymore for new sales.

**Comment by Zimulakra** [comment]
This recent sale seems to have a duplicate event.
https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/cd81caf68e513fa5a24277f6c95eb0866f8e63fc60c4573591443df3e1a3b55a

**Comment by maritsaart** [comment]
Same issue:

https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/6853695fc8846a3ffee2ea04d407e9d75ae280991b5cf46cb8ab98db5b9f1d0a

![Sales history shows each event twice01](https://user-images.githubusercontent.com/99899807/230342447-f4c4b06e-ade0-40b3-bb60-e3101072e3d7.jpg)
