### ISSUE TITLE
Wallet Error - Not enough witnesses when trying to buy

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#42]
I get this error -
Wallet error: Transaction signing error: Prover error (tx input index 0): Failed on step2(prover does not have enough witnesses to perform the proof)

When I try to bid on this - 
https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/22c7bb271a9de68a905ef22a698baa90e3827a706b3615eda24cfba8e81db277

**Comment by anon-real** [comment]
This auction is broken. Please let us know if you see this error for any other listings.
