### ISSUE TITLE
Wrong collection volume

### ISSUE THREAD

**Issue by maritsaart** [ergo-auction-house/frontend#44]
Account: https://auctionhouse-testnet-qa78f.ondigitalocean.app/user/3WyQ3QNcfmTrj2rgGgenek9TRLUh4jVBz8X58oKNTRkubBHNiatZ?tab=3

Collection: https://auctionhouse-testnet-qa78f.ondigitalocean.app/collection/40079564400a398c5a2cf8effd45aceef50fdca47b574ef26c4ce1d5f34a37ac

Sold work (via "fixed price") not included in scope:
"Ladscape 1x2"
https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/cd6ad1c98cdee8a53cad131b2462b9be549c010d6c8ac81210b9dd6ac184d971

Collection volume must be: 4 + 10 + 5.98 + 1 = 20.98
Collection volume        : 4 + ? + 5.98 + 1 = 10.98
 
![WrongVolume01](https://user-images.githubusercontent.com/99899807/230312392-266bc23e-e25c-464f-b1e5-5bb41b314138.jpg)
![WrongVolume02](https://user-images.githubusercontent.com/99899807/230312396-499f6cf5-b453-43fb-9cc0-63b07f90ca9e.jpg)

**Comment by pyotrsky** [comment]
We re-iterated the Ergo network and tried to fix a few bugs. Would you review the problem you mentioned and see if it persists? @maritsaart

**Comment by maritsaart** [comment]
Looks like it's fixed

**Comment by maritsaart** [comment]
How can I burn NFT on testnet (to test how AРм3 handles  with duplicates)

**Comment by maritsaart** [comment]
@anon-real
How can I burn NFT on testnet (to test how AHv3 handles with duplicates)?

**Comment by anon-real** [comment]
@maritsaart I don't think there is an easy option for that on testnet.
However, we don't consider burning currently. Will think about it.

**Comment by maritsaart** [comment]
Based on the experience of two years of working with NFT, I can say that for an artist, burning NFT due to errors is the norm of the workflow. I even calculated: due to flaws, I had to burn and remint 3.5% of the tokens (out of 450+).

**Comment by maritsaart** [comment]
@anon-real
Based on the experience of two years of working with NFT, I can say that for an artist, burning NFT due to errors is the norm of the workflow. I even calculated: due to flaws, I had to burn and remint 3.5% of the tokens (out of 450+).

**Comment by maritsaart** [comment]
Perhaps it would be better to move the last comments to a new issue and mark it as "enhancement"?

**Comment by anon-real** [comment]
@maritsaart I'll add another issue for burning. Closing this!
