### ISSUE TITLE
Lowercase in trait name during minting

### ISSUE THREAD

**Issue by maritsaart** [ergo-auction-house/frontend#45]
Item: https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/8e3982cfd974ea411ff002b5671a4fddd0256440db293ecfaa5771803d784bda

Now    : x, y, width, height, xxxxxxxx, yyyyyyyy
Must be: X, Y, Width, Height, XxxxXxxx, YyyyYyyy

![LowercaseInTraitNameDuringMinting01](https://user-images.githubusercontent.com/99899807/230322528-c11caf0e-67a6-4f9f-9779-28d681c06f73.jpg)
![LowercaseInTraitNameDuringMinting02](https://user-images.githubusercontent.com/99899807/230322532-920e51a4-cef0-45f0-a045-55932c10731b.jpg)
![LowercaseInTraitNameDuringMinting03](https://user-images.githubusercontent.com/99899807/230322534-9949f5d6-7bc7-4da9-883f-398eb8eeb11e.jpg)

**Comment by anon-real** [comment]
Traits are case-insensitive. We should make all keys uppercase. @imght
