### ISSUE TITLE
The mark is poorly visible when matching the NFT color

### ISSUE THREAD

**Issue by maritsaart** [ergo-auction-house/frontend#46]
![Issue46_The mark is poorly visible when matching the NFT color01](https://user-images.githubusercontent.com/99899807/230340633-2dad0662-4e5b-4e6b-905d-5b02fe8c0fc9.jpg)

**Comment by anon-real** [comment]
For items in My Artworks and My Collections tabs, we should add "Select" button instead of "See more" which selects the card since we no longer are showing the auction information. @imght

**Comment by anon-real** [comment]
This should be fixed now.
