### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by anon-real** [ergo-auction-house/frontend#47]
<img width="843" alt="Screenshot 2023-04-06 at 7 36 09 PM" src="https://user-images.githubusercontent.com/68861503/230529660-047197c6-9516-4c54-8a55-af09689f881d.png">

You can see that the results in the dropdown are fine but the page shows "No items found"

**Comment by ERGkleure** [comment]
![1](https://user-images.githubusercontent.com/90791980/231075596-734a9859-e5c9-472c-9ad5-d7732bb12c95.png)

![2](https://user-images.githubusercontent.com/90791980/231075625-ce43ab13-1859-4c43-8eb9-824d42911db2.png)

I was going to comment the same thing, that the search was not working, but I saw that the error had already been detected.

**Comment by anon-real** [comment]
This should be fixed.
