### ISSUE TITLE
Old collections (minted before EIP-34)

### ISSUE THREAD

**Issue by maritsaart** [ergo-auction-house/frontend#48]
@anon-real earlier you wrote
[discord #development](https://discord.com/channels/668903786361651200/669989266478202917/1050212670302855269)
12/08/2022
_- We are thinking about importing other marketplaces' data such as sales and collections to AH which makes our price history and transition for artists very easy. For sales, it is easy. For collections since other marketplaces, unfortunately, started having collections without an EIP, collections they have are basically centralized and written only in some DB._ **Still, we are thinking of ways to let artists have their already existing collections in the new AH.**

I have more than 40 collections at 3 addresses, I am very interested in this feature 🙏 
[twitter maritsaart - collections overview](https://twitter.com/maritsaart/status/1645393827996344322)

**Comment by anon-real** [comment]
Yes, this is still our plan.

**Comment by maritsaart** [comment]
@anon-real 
[_"there was no standard to be backward compatible for"_](https://github.com/ergo-auction-house/frontend/issues/76#issuecomment-1593729957) - and who is stopping you from making changes or making a second / third version of the standard? You are an author and developer of this EIP.

_"Technically, the proposed solutions (just showing metadata in the UI)"_
I don't understand the passage about UI. I propose to store the list of NFT IDs on the blockchain in an AHv3 collection token (or something similar). Yes, there could be problems. For example, with the scam attempt to add NFTs from other authors. But this can be solved at the creation stage - allow only those NFTs that was minted on the address**ES** (**1+**!) associated with the account.

There is an example of a **token with a list of IDs** in my **amateur** MVP for the "Collection token" and the "Linked storage" (autumn 2022): [Token with list of tokenIDs in [R5]](https://ergotokens.org/#/?token=4816d70f2eae4916062433776ad43c86f84e27d735392cb5c8b133ae2ba96f0b), [Tx](https://explorer.ergoplatform.com/en/transactions/9f66f60afb08a3e862a93e298eec23c511f12e7ed321cc8019dc4e7502454cd9)


**Offtopic**
[Collection Token](https://ergotokens.org/#/?token=9a6868fe36d2688ee4bb801e9b3b70e85a3242da6c7a5fadc2f0d21b240a695d) - on-chain svg in [R9] with JS script which use data from **token with a list of IDs**, loading and showing all images as grid (see screenshot). With this MVP I tried to solve two problems:
1) somehow bypass the 4Kb limit for on-chain image storage (for more or less interesting images, I need 10-25Kb);
2) somehow organize tokens from collections minted before the adoption of the EIP-0034 standard (I have 40+ collections in different styles).

Full version on Discord: [MVP](https://discord.com/channels/668903786361651200/669989266478202917/1082384511188349029), [why MVP and why stopped](https://discord.com/channels/668903786361651200/669989266478202917/1082940272914206730)
Some explanations: [vulnerabilities](https://discord.com/channels/668903786361651200/669989266478202917/1082577284684333106), [expl2](https://discord.com/channels/668903786361651200/669989266478202917/1082577988299784273), [why stop](https://discord.com/channels/668903786361651200/669989266478202917/1082579675248857098)

![Animal_pop_art_00_Collection_Token](https://github.com/ergo-auction-house/frontend/assets/99899807/fa3eb7d1-ab33-4421-883b-316fb188f155)

**Comment by maritsaart** [comment]
@anon-real
> **maritsaart** **(1)** _"allow only those NFTs that was minted on the addressES (1+!) associated with the account."_
>> **anon-real** "blockchain is permissionless, we can not enforce people not to do something in the UI only. Contracts should enforce that."_

When minting a collection, a list of associated address**ES** is determined. What prevents you from doing check **(1)** in a smart contract?

AH team do collections verification outside the blockchain, by people's hands. There are not many Ergo's OGs with the problem of this topic. I think up to 20 artists, half of them are inactive for a year+ and will not return to Ergo. Therefore, the argument that check **(1)** can only be done on the blockchain is very controversial.
So I don't understand why check **(1)** can't be done on the AH site backend. Or even in manual mode for those 10-20 artists - I mean minting some specific token or SC with specific rules or ... - you know better.

**Comment by maritsaart** [comment]
@anon-real earlier you wrote
[discord #development](https://discord.com/channels/668903786361651200/669989266478202917/1050212670302855269)
12/08/2022
_- We are thinking about importing other marketplaces' data such as sales and collections to AH which makes our price history and transition for artists very easy. For sales, it is easy. For collections since other marketplaces, unfortunately, started having collections without an EIP, collections they have are basically centralized and written only in some DB._ 

Any news on import SkyHarbor sales history to AH v.3?

Animal pop art #26. Turtle
[SH Sale:](https://www.skyharbor.io/token/3d8275625c4ed1679b4ad72d0a6ed0fd79ed35ab6b63abbdf59f9d03d15eae51) 50 ERG 19.11.2023 [Tx](https://explorer.ergoplatform.com/en/transactions/cbff65f4f089e095b2c562d31d92c4a33b20a96616690f5ade40519cf9b6ac37)

[AH v.3:](https://ergoauctions.org/artwork/3d8275625c4ed1679b4ad72d0a6ed0fd79ed35ab6b63abbdf59f9d03d15eae51) ***No sales yet!***
