### ISSUE TITLE
In Notifications - artwork thumbnail aspect ratio

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#5]
In the notifications dropdown, a 16x9 artwork shows up in square format. It is squished.
<img width="435" alt="aspect_ratio" src="https://user-images.githubusercontent.com/129136234/228122727-d7366457-379f-4991-b7d7-7fa8a0000623.png">

**Comment by Therisaa** [comment]
I fixed this issue. The image's aspect ratio in notifications is now similar to the original aspect ratio. Would you please check it again?
