### ISSUE TITLE
Can't enter Twitter handle to connect account

### ISSUE THREAD

**Issue by WalrusDAO** [ergo-auction-house/frontend#54]
![Screenshot 2023-05-27 141533](https://github.com/ergo-auction-house/frontend/assets/114140105/a0a2e6fd-fac9-495b-89b8-084b77abccdf)

**Comment by anon-real** [comment]
You don't need to enter anything. Just click on verify.

**Comment by WalrusDAO** [comment]
Then I get this:
![Screenshot 2023-05-27 153248](https://github.com/ergo-auction-house/frontend/assets/114140105/73721988-4610-49cb-9cdc-1ab1aca6c6d4)
