### ISSUE TITLE
Where is the Mass minter on the new site !!?

### ISSUE THREAD

**Issue by ErgClay** [ergo-auction-house/frontend#58]
I can't find how to mint my whole generated collection with its metadata !!!?

**Comment by anon-real** [comment]
Hi, you can issue up to 100 artworks at once in the new version. For that you can set the a set of default values and traits and in the next page update them individually.
Next feature we'll add is reading the metadata from file.

**Comment by ErgClay** [comment]
thanks alot for your very useful reply , Sure I will try this method
