### ISSUE TITLE
Stuck on "Connection to your wallet" while trying to list

### ISSUE THREAD

**Issue by mgpai22** [ergo-auction-house/frontend#6]
<img width="502" alt="stuck" src="https://user-images.githubusercontent.com/64056966/228130503-cddeb355-1fb5-41f3-83a7-11cef1e58116.png">

**Comment by anon-real** [comment]
@mgpai22 Could you provide more details?

How many artworks were you listing? What kind of listing (timed, fixed, ...)

Also, if you are still having this issue, please open your network and see if any request fails. If it does please provide the payload for that endpoint. That would help us a lot figuring out what is happening.

**Comment by mgpai22** [comment]
Seems to have been resolved. If it happens again I will provide more info.
