### ISSUE TITLE
Trouble connecting wallet to AH

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#63]
I'm able to connect a test wallet to the AH with Nautilus, but when I try to connect my main wallet (9en2JxyCnQgjgRCaFMXBX87z1VcGjVvd3yug2GVmJXRHw59Evgz) it does not work. 

It looks like an error message pops up for a mili-second after I enter my password, but it's too fast to read.

**Comment by HelixEvo** [comment]
Having similar issue. For me if Nautillus has more than one wallet, it always picks the one I added first, there is not an option to pick which wallet to connect to AH with... It does look like it flashes something up, but too quick to tell.

This was using Chrome.

**Comment by anon-real** [comment]
You can disconnect the wallet from the UI in the connected dapps of Nautilus.

**Comment by HelixEvo** [comment]
> You can disconnect the wallet from the UI in the connected dapps of Nautilus.

That did it. Thanks!
