### ISSUE TITLE
Importing or Creating a Collecttion Hang / Firefox

### ISSUE THREAD

**Issue by HelixEvo** [ergo-auction-house/frontend#64]
When using Firefox and trying to create a new collection (Import from Sky Harbor or New) the process hangs at 0% "Uploading Images"

Collection never completes. Gave it 5 minutes.

**Comment by anon-real** [comment]
Have you tried chrome?

**Comment by HelixEvo** [comment]
Oh my. Chrome experience, night and day compared to Firefox.

Flows and works loads better.
