### ISSUE TITLE
Can't see a way to remove Twitter verification

### ISSUE THREAD

**Issue by HelixEvo** [ergo-auction-house/frontend#65]
I had added a wallet earlier today and verified Twitter.

Twitter stayed logged in as that account; I was adding another wallet later in the day to AH and went to verify Twitter.... Unfortunatly it went straight to the first account on Twitter I was still connected to and has used that on AH.

I don't see any ways on how to remove the Twitter verification so I can use different Twiiter account for correct verification.

Currently now two profiles on AH with the same name but different wallets, as they both used the same Twitter account.

**Comment by anon-real** [comment]
Okay, we are working on disconnecting the twitter account. It may take a day or two though. Could you send me the profile you want to get disconnected?
