### ISSUE TITLE
NFTs not showing up under "Owned Artorks"

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#68]
I have over 130 NFTs in my minting wallet
https://ergowallets.org/wallet/9en2JxyCnQgjgRCaFMXBX87z1VcGjVvd3yug2GVmJXRHw59Evgz

Only 44 of them show up under "Owned Artworks"

I don't think AHv3 is resolving the R9 link
for example this NFT --
https://ergotokens.org/#/?token=c64cfe4735d609951afeeab4d3b39403dc23e1ff9c4630c836429e7e8a14f9ba

R9 (Optional) - Link to the artwork (UTF-8 representation)
Optional - link to the artwork (UTF-8 representation)
https://i.ibb.co/jyff2XM/everythingisfear-flwr-man-sm.png

**Comment by anon-real** [comment]
Please contact me over discord to investigate this.

**Comment by maritsaart** [comment]
Same issue

I have over 440 NFTs + 30+ FTs in my minting wallets
**9gsiBLZowvDWtZ7wHuWZmv58LFqMfCEW4XepV9AYtr7HofPhFqJ** (current)
**9euNAMKJwzBE8bvNtkMbS9k8moLJXfXVM3BtW1XspWpVLtjNLVw** (old from early '21)
**9fve6n3dFYdGsHepEjVWpz8ZS9trWSWmgyHocLwvymwzZeyTxZt** (tokenart on-chain NFTs)

Only 224 of them show up under collection imported from SH:

[https://ergoauctions.org/collection/9fe56413e334d7445f614327e455b6cc48849a8fb3536fea40b8c6ec75ddd18c?tab=](https://ergoauctions.org/collection/9fe56413e334d7445f614327e455b6cc48849a8fb3536fea40b8c6ec75ddd18c?tab=)

It looks like NFTs weren't imported from the **9euN...NLVw** and **9fve...TxZt** addresses.

Examples:
[**ergotokens** Animal pop art #01. Zebra](https://ergotokens.org/#/?token=8c25f0652ca09a6a60b00467521cd3e6d2faf742727a1d04982d72978a557493) -- [**AH** 404](https://ergoauctions.org/artwork/8c25f0652ca09a6a60b00467521cd3e6d2faf742727a1d04982d72978a557493)
[**ergotokens** Animal pop art #02. Giraffe](https://ergotokens.org/#/?token=f27c89018a4a347b915d0987d2c9a254bcd1141b9ddc2704f7748ffa97403669) -- [**AH** 404](https://ergoauctions.org/artwork/f27c89018a4a347b915d0987d2c9a254bcd1141b9ddc2704f7748ffa97403669)
[**ergotokens** Animal pop art #03. Rabbit](https://ergotokens.org/#/?token=366731470a52e89bea0b26beaf12956c3868c8c08c1598fa6eda2936778f5fad) -- [**AH** 404](https://ergoauctions.org/artwork/366731470a52e89bea0b26beaf12956c3868c8c08c1598fa6eda2936778f5fad)
[**ergotokens** Character #02 Ergo Girl](https://ergotokens.org/#/?token=7a9e87b486b4c6310cc4d23597981263947a248a6954c5d0253df918e8275eb0) -- [**AH** 404](https://ergoauctions.org/artwork/7a9e87b486b4c6310cc4d23597981263947a248a6954c5d0253df918e8275eb0)


Also not scanned or displaying fungible tokens (text tokenart in R5 register).
Example:
[**ergotokens** Tokenart Bull #1](https://ergotokens.org/#/?token=5bf4c560910c3210642001da85c5d36d65325aaedfcb9152faae7337a402f1c4) -- [**AH** 500](https://ergoauctions.org/artwork/5bf4c560910c3210642001da85c5d36d65325aaedfcb9152faae7337a402f1c4)

**Comment by anon-real** [comment]
This should be resolved. @Zimulakra @maritsaart please confirm.

**Comment by maritsaart** [comment]
@anon-real 
Yes, old NFTs are now displayed! Thank you!

**Comment by maritsaart** [comment]
@anon-real 

Remaining problems:
1. On-chain tokenart FT (register R5) is not displayed (AHv2 displayed these FTs), example: 
AHv3 - ERR: [Tokenart Panda #1](https://ergoauctions.org/artwork/f19360e92ecd5161a8325c6088925f8d58dff849765281603b9e4e606ae549eb
)

_Application error: a client-side exception has occurred (see the browser console for more information)._
![FT_not_showing](https://github.com/ergo-auction-house/frontend/assets/99899807/a6ee17d3-a4d7-4c57-9978-f6393ee4f240)

ErgExplorer - OK : [Tokenart Panda #1](https://ergexplorer.com/token#f19360e92ecd5161a8325c6088925f8d58dff849765281603b9e4e606ae549eb)


In ErgExplorer all my [tokenart FTs in R5](https://ergexplorer.com/issued-tokens#query=tokenart&offset=0&hideBurned=true&order=nameAsc&type=token) looks perfect. Can you do the same?

**How to** by ErgExplorer Dev, **AcoSmrkas** in [discord](https://discord.com/channels/668903786361651200/1109109426465542235/1118563419331772447) +/-10 comments up/down:
> _Windows FF/Chrome/Edge/Brave... Checked which font was being used on Ubuntu Firefox and downloaded that one. Replaced newlines with < br> and wrapped in < pre> tag. ... reduce the line height (css), as in ergoexplorer and ergotokens? To minimize line spacing._


_


_
2. Burnt NFTs/FTs are still displayed, example: [Animal pop art #06. Rhinoceros](https://ergoauctions.org/artwork/26a1d5793800783468149f4c39abb157e3ee06d60e92d31f036eec630b8a533f)
Can you mark/**hide** burned NFTs/FTs as [ErgExplorer does](https://ergexplorer.com/addresses#9euNAMKJwzBE8bvNtkMbS9k8moLJXfXVM3BtW1XspWpVLtjNLVw): 
+ Red status/mark **(Burned)**, [example](https://ergexplorer.com/token#26a1d5793800783468149f4c39abb157e3ee06d60e92d31f036eec630b8a533f)
+ burned NFTs/FTs placed at the end, alphablended or filtered at all, [example:](https://ergexplorer.com/addresses#9euNAMKJwzBE8bvNtkMbS9k8moLJXfXVM3BtW1XspWpVLtjNLVw)
![Burned_NFTs](https://github.com/ergo-auction-house/frontend/assets/99899807/a4a52ff3-c89e-4a1a-9848-87109162d977)

**How to manage** burned tokens by **hq3r**, **qx()** and other in ErgExplorer chat: [discord](https://discord.com/channels/668903786361651200/1109109426465542235/1118848788778451004) +/-20 comments up/down

**Comment by anon-real** [comment]
@maritsaart for token burning, there is a separate issue.

For tokenart, AH v3 yet doesn't support ordinary artworks. It is in our backlog to support them.

But since your tokens are not following any specific standard (R7 register is empty) and it seems impossible to detect what is "tokenart", it may not be possible.

I'm going to close this issue since the main issue is resolved. Feel free to open new one if needed.

**Comment by maritsaart** [comment]
@anon-real Thanks! Last comments copied to https://github.com/ergo-auction-house/frontend/issues/85 and https://github.com/ergo-auction-house/frontend/issues/87
