### ISSUE TITLE
Sales history shows each event twice

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#7]
https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/67b08b7ad0c350cb97cf33a027cd7d1b2e64affe27d3bf1682aed66bdaccc16a

<img width="711" alt="Sales" src="https://user-images.githubusercontent.com/129136234/228388891-55641a87-52cb-4c9a-acec-a346664686c1.png">

**Comment by 11001101110101110001111010111110101** [comment]
This problem has been fixed. Please check it now.

**Comment by anon-real** [comment]
We believe this has been fixed but we should still test! Closing this for now.

**Comment by maritsaart** [comment]
Same issue

Item: https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/6853695fc8846a3ffee2ea04d407e9d75ae280991b5cf46cb8ab98db5b9f1d0a

![Sales history shows each event twice01](https://user-images.githubusercontent.com/99899807/230338993-52fb0da3-99bd-45c3-9e98-f1b706341986.jpg)

UPD:
Fixed here https://github.com/ergo-auction-house/frontend/issues/44#issuecomment-1499829599
