### ISSUE TITLE
Wallet sign in / bid 

### ISSUE THREAD

**Issue by DoctoredDouglass** [ergo-auction-house/frontend#78]
I’m having issues signing in. When I try to connect my wallet and or bid I get the attached message in nautilus. 
![nautilus_AH](https://github.com/ergo-auction-house/frontend/assets/135738760/5398ab1d-57d0-43c9-a12a-5c2ce479334f)
![Nautilus_AH2](https://github.com/ergo-auction-house/frontend/assets/135738760/b4163f46-568f-4fa9-b580-39e2153b2bd5)

**Comment by ERGkleure** [comment]
@DoctoredDouglass I understand that's normal, it's how the transaction is composed and all of that will come back to your wallet. Anyway, @anon-real will surely be able to give you more details.

**Comment by anon-real** [comment]
@DoctoredDouglass that's normal. The transaction won't be broadcasted.
