### ISSUE TITLE
Unable to change name and twitter

### ISSUE THREAD

**Issue by Lycan2022** [ergo-auction-house/frontend#79]
I logged into my wallets, wanting to see if I could change the twitter accounts. I now see that both seem locked out of and disconnected from twitter. I cannot change the name, or get them linked to a twitter account. 
Additionally collection name has dissappeared for both my collections Lycan Trope and Lycan Labs (see screenshots)

![IMG_20230608_113036_191.jpg](https://github.com/ergo-auction-house/frontend/assets/120051677/2b777a61-d5ae-47c6-8957-b4fcef0a150b)

![IMG_20230608_113032_304.jpg](https://github.com/ergo-auction-house/frontend/assets/120051677/b867b48f-0ec2-4470-93a0-9434da242a03)

Anon mentioned it was an bug to be able to log two wallets on the same twitter account in the first place.

See also @anon-real in https://github.com/ergo-auction-house/frontend/issues/76#issuecomment-1579598552_

**Comment by 11001101110101110001111010111110101** [comment]
can you please check it now? Log in to twitter fixed right now.

**Comment by 11001101110101110001111010111110101** [comment]
can you please send me your collections' tokenId? I need one more favor: please log out and log in again into your wallet.

**Comment by Lycan2022** [comment]
Will do both as soon as I get to my laptop, and give an update . Thanks for addressing 🙏🤍

**Comment by Lycan2022** [comment]
Problem solved! 😄
