### ISSUE TITLE
Error Message when trying to buy fixed price NFT

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#8]
Tried to buy this (also happened on another fixed price NFT)
https://auctionhouse-testnet-qa78f.ondigitalocean.app/artwork/1622a9d6b36acae5893fcc4ded6c8c700dfcae6437a46d4e066d9d3904242e7c

Popup said "Connecting to your wallet", then my wallet popped up but the message was still there.

After I entered my password, I got this error
Wallet error: Transaction signing error: Prover error (tx input index 0): Failed on step2(prover does not have enough witnesses to perform the proof)

<img width="661" alt="witnesses" src="https://user-images.githubusercontent.com/129136234/228389962-beda452c-1b41-466c-bbd8-39753a19b665.png">

**Comment by pyotrsky** [comment]
The artwork you're trying to buy seems to have an issue. The buy transaction can't be signed. Would you please try another fixed-price auction? @Zimulakra

**Comment by Zimulakra** [comment]
Buying other fixed price auctions works fine.
