### ISSUE TITLE
Completed auction displayed in listings

### ISSUE THREAD

**Issue by maritsaart** [ergo-auction-house/frontend#80]
This NFT [Mask Aboriginal #0023](https://ergoauctions.org/artwork/fad99ece90838167fd7ad67118a5adff146935773ece9293bd58791aca126272), [ergotokens](https://ergotokens.org/#/?token=fad99ece90838167fd7ad67118a5adff146935773ece9293bd58791aca126272) has already been sold 18.12.2021 to **9hKE...DFYx**:
+ [AHv2 link](https://ergoauctions.org/#/auction/specific/08d0eda55fb037fc6808de27ccd7090e2b56240113dfc5998cffd09e9bc50194) (link not working, we waiting for _v2.auctionhouse.org_)
+ [sale transaction](https://explorer.ergoplatform.com/en/transactions/c95dcb5f26d57871f8387a9a69a771bb98f5e2e642eded3375e63804b4da7fa3) 

AH v2 parameters (2021.12.17):
Minimum Bid: 12.0
Minimum Step: 0.5
Instant Buy Amount: 32.0
Auction End Time: 22.03.2022

But now it is displayed in the listings tab of my [current wallet](https://ergoauctions.org/user/9gsiBLZowvDWtZ7wHuWZmv58LFqMfCEW4XepV9AYtr7HofPhFqJ?tab=2&tabName=listings) with the parameters of the 2021 auction (Minimum Bid/Instant Buy):
![Old_auction](https://github.com/ergo-auction-house/frontend/assets/99899807/a0478dcb-918b-4450-ab0a-0c529abcbd7d)

**Comment by anon-real** [comment]
Thanks for reporting. This issue is known and is related to some of the missing artwork you have. Will be resolved soon.

**Comment by maritsaart** [comment]
Fixed!
