### ISSUE TITLE
NFTs (edition of 3) shows up weird

### ISSUE THREAD

**Issue by Zimulakra** [ergo-auction-house/frontend#9]
I made this NFT in an edition of 3
5091cda2371719eed0d7c07624f8d116e77a9f91232c4e7e69489b29097e6703

I put 2 up for auction and one is just in my wallet.

Under my Profile "Artworks", only one of the ones up for auction shows up.
Under my Profile "Auctions", both auctions show up correctly.
Under my Profile "My Arworks", only one of the ones up for auction shows up.

--
If there is an edition of 3 and two are up for auction, I would think there would be as separate thumbnail for each activity going on. One is fixed price auction, one is descending auction and one is just being held.

**Comment by pyotrsky** [comment]
The behavior of the "Auctions" tab is as expected. We need to change the behavior of the other two tabs, such that all copies of the same artwork be treated similarly.

**Comment by anon-real** [comment]
@imght I believe this has been done?
